name: Node.js CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        node-version: [18.x]
        os: [ubuntu-latest, windows-latest, macos-latest]

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: npm ci
    - run: npm run build --if-present
    
    - name: Unit tests
      run: npm test

    - run: npm install serve -g

    - if: "${{matrix.os != 'windows-latest'}}"
      run: npx serve -s build & echo "System running on http://localhost:3000/"

    - if: "${{matrix.os == 'windows-latest'}}"
      run: Start-Process -WindowStyle Minimized -FilePath npx -ArgumentListserve -s build

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'

    - name: Use software
      uses: browser-actions/setup-chrome@v1

    - name: Install the necessary packages
      run: pip install requests webdriver_manager selenium pytest

    - name: Run the PytTest script
      run: pytest system_tests/ -rA
